[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.20.5"
  NPM_VERSION = "10.8.2"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true


[[headers]]
  for = "/*"
  [headers.values]
   Cache-Control = "public, max-age=0, must-revalidate"
   X-Frame-Options = "DENY"